### YamlMime:ManagedReference
items:
- uid: Finalassignment.GlobalConfiguration
  commentId: T:Finalassignment.GlobalConfiguration
  id: GlobalConfiguration
  parent: Finalassignment
  children:
  - Finalassignment.GlobalConfiguration.IsFillEnabled
  - Finalassignment.GlobalConfiguration.MaxX
  - Finalassignment.GlobalConfiguration.MaxY
  - Finalassignment.GlobalConfiguration.OutputExceptionMsg
  langs:
  - csharp
  - vb
  name: GlobalConfiguration
  nameWithType: GlobalConfiguration
  fullName: Finalassignment.GlobalConfiguration
  type: Class
  source:
    remote:
      path: Finalassignment/GlobalConfiguration.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-drccd.git
    id: GlobalConfiguration
    path: GlobalConfiguration.cs
    startLine: 8
  assemblies:
  - Finalassignment
  namespace: Finalassignment
  syntax:
    content: public class GlobalConfiguration
    content.vb: Public Class GlobalConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Finalassignment.GlobalConfiguration.MaxX
  commentId: P:Finalassignment.GlobalConfiguration.MaxX
  id: MaxX
  parent: Finalassignment.GlobalConfiguration
  langs:
  - csharp
  - vb
  name: MaxX
  nameWithType: GlobalConfiguration.MaxX
  fullName: Finalassignment.GlobalConfiguration.MaxX
  type: Property
  source:
    remote:
      path: Finalassignment/GlobalConfiguration.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-drccd.git
    id: MaxX
    path: GlobalConfiguration.cs
    startLine: 30
  assemblies:
  - Finalassignment
  namespace: Finalassignment
  syntax:
    content: public static int MaxX { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxX As Integer
  overload: Finalassignment.GlobalConfiguration.MaxX*
- uid: Finalassignment.GlobalConfiguration.MaxY
  commentId: P:Finalassignment.GlobalConfiguration.MaxY
  id: MaxY
  parent: Finalassignment.GlobalConfiguration
  langs:
  - csharp
  - vb
  name: MaxY
  nameWithType: GlobalConfiguration.MaxY
  fullName: Finalassignment.GlobalConfiguration.MaxY
  type: Property
  source:
    remote:
      path: Finalassignment/GlobalConfiguration.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-drccd.git
    id: MaxY
    path: GlobalConfiguration.cs
    startLine: 52
  assemblies:
  - Finalassignment
  namespace: Finalassignment
  syntax:
    content: public static int MaxY { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Shared Property MaxY As Integer
  overload: Finalassignment.GlobalConfiguration.MaxY*
- uid: Finalassignment.GlobalConfiguration.IsFillEnabled
  commentId: P:Finalassignment.GlobalConfiguration.IsFillEnabled
  id: IsFillEnabled
  parent: Finalassignment.GlobalConfiguration
  langs:
  - csharp
  - vb
  name: IsFillEnabled
  nameWithType: GlobalConfiguration.IsFillEnabled
  fullName: Finalassignment.GlobalConfiguration.IsFillEnabled
  type: Property
  source:
    remote:
      path: Finalassignment/GlobalConfiguration.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-drccd.git
    id: IsFillEnabled
    path: GlobalConfiguration.cs
    startLine: 74
  assemblies:
  - Finalassignment
  namespace: Finalassignment
  syntax:
    content: public static bool IsFillEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Shared Property IsFillEnabled As Boolean
  overload: Finalassignment.GlobalConfiguration.IsFillEnabled*
- uid: Finalassignment.GlobalConfiguration.OutputExceptionMsg
  commentId: P:Finalassignment.GlobalConfiguration.OutputExceptionMsg
  id: OutputExceptionMsg
  parent: Finalassignment.GlobalConfiguration
  langs:
  - csharp
  - vb
  name: OutputExceptionMsg
  nameWithType: GlobalConfiguration.OutputExceptionMsg
  fullName: Finalassignment.GlobalConfiguration.OutputExceptionMsg
  type: Property
  source:
    remote:
      path: Finalassignment/GlobalConfiguration.cs
      branch: main
      repo: https://github.com/ASE-Classroom/ase-demo-assignment-drccd.git
    id: OutputExceptionMsg
    path: GlobalConfiguration.cs
    startLine: 94
  assemblies:
  - Finalassignment
  namespace: Finalassignment
  syntax:
    content: public static string OutputExceptionMsg { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared Property OutputExceptionMsg As String
  overload: Finalassignment.GlobalConfiguration.OutputExceptionMsg*
references:
- uid: Finalassignment
  commentId: N:Finalassignment
  href: Finalassignment.html
  name: Finalassignment
  nameWithType: Finalassignment
  fullName: Finalassignment
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Finalassignment.GlobalConfiguration.MaxX*
  commentId: Overload:Finalassignment.GlobalConfiguration.MaxX
  href: Finalassignment.GlobalConfiguration.html#Finalassignment_GlobalConfiguration_MaxX
  name: MaxX
  nameWithType: GlobalConfiguration.MaxX
  fullName: Finalassignment.GlobalConfiguration.MaxX
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: Finalassignment.GlobalConfiguration.MaxY*
  commentId: Overload:Finalassignment.GlobalConfiguration.MaxY
  href: Finalassignment.GlobalConfiguration.html#Finalassignment_GlobalConfiguration_MaxY
  name: MaxY
  nameWithType: GlobalConfiguration.MaxY
  fullName: Finalassignment.GlobalConfiguration.MaxY
- uid: Finalassignment.GlobalConfiguration.IsFillEnabled*
  commentId: Overload:Finalassignment.GlobalConfiguration.IsFillEnabled
  href: Finalassignment.GlobalConfiguration.html#Finalassignment_GlobalConfiguration_IsFillEnabled
  name: IsFillEnabled
  nameWithType: GlobalConfiguration.IsFillEnabled
  fullName: Finalassignment.GlobalConfiguration.IsFillEnabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Finalassignment.GlobalConfiguration.OutputExceptionMsg*
  commentId: Overload:Finalassignment.GlobalConfiguration.OutputExceptionMsg
  href: Finalassignment.GlobalConfiguration.html#Finalassignment_GlobalConfiguration_OutputExceptionMsg
  name: OutputExceptionMsg
  nameWithType: GlobalConfiguration.OutputExceptionMsg
  fullName: Finalassignment.GlobalConfiguration.OutputExceptionMsg
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
